// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yuque.EFCore.DbContexts;

#nullable disable

namespace Yuque.WebAPI.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260423072520_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yuque.Core.Entities.AsyncTasks.AsyncTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AsyncTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("KnowledgeBaseId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Attachment", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Anchor")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long?>("KnowledgeBaseEntryId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentId");

                    b.ToTable("Comment", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.CommentMention", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long>("MentionedUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("CommentId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("CommentMention", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("KnowledgeBaseEntryId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("KnowledgeBaseEntryId")
                        .IsUnique();

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("Document", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.DocumentPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<short>("Permission")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "UserId")
                        .IsUnique();

                    b.ToTable("DocumentPermission", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.DocumentVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "VersionNo")
                        .IsUnique();

                    b.ToTable("DocumentVersion", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Favorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long?>("KnowledgeBaseEntryId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<short>("TargetType")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "KnowledgeBaseEntryId");

                    b.HasIndex("UserId", "KnowledgeBaseId");

                    b.ToTable("Favorite", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.KnowledgeBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<short>("Visibility")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "Slug")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("KnowledgeBase", null, t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.KnowledgeBaseEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<short>("EntryType")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId", "ParentId");

                    b.HasIndex("KnowledgeBaseId", "ParentId", "Slug")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("KnowledgeBaseEntry", null, t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.KnowledgeBaseMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("KnowledgeBaseId", "UserId")
                        .IsUnique();

                    b.ToTable("KnowledgeBaseMember", null, t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.ToTable("Notification", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.ShareLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset?>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long?>("KnowledgeBaseEntryId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("KnowledgeBaseId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ShareLink", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasComment("");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Type", "OwnerUserId");

                    b.ToTable("Team", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Knowledge.TeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long?>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasComment("");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMember", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.OpenAppConfigs.AppConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<long?>("AccessValidTime")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Sessionkey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.OpenAppConfigs.AppEventConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("EventCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("HookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppEventConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.OpenAppConfigs.AppNotificationConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("NoticeUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Phones")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppNotificationConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.OpenAppConfigs.AppWebhookConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("HookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Method")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("AppWebhookConfig", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Schedules.ScheduleTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTimeOffset>("LastExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("NextExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("ScheduleTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Schedules.ScheduleTaskRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("ExecuteEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<DateTimeOffset>("ExecuteStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<DateTimeOffset>("ExpressionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("ScheduleTaskId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTaskId");

                    b.ToTable("ScheduleTaskRecord", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Schedules.SeedDataTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("ConfigPath")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<int>("ExecuteStatus")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("ExecuteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("SeedDataTask", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.ApiResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("NameSpace")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("RoutePattern")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("ApiResource", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.DownloadItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("bucket")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("DownloadItem", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<long>("OriginalId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("File", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.GlobalSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveIcon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<int>("ActiveIconType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Icon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<int>("IconType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("IdSequences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsExternalLink")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menu", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.MenuResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiResourceId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("ApiResourceId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuResource", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("ErrorTracker")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("LogType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("OperationContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("OperationMenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("OperationLog", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("IdSequences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("Region", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<int>("DataRange")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permission", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("Platforms")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("Role", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<DateTimeOffset>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasComment("");

                    b.Property<string>("NickName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("RealName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("");

                    b.HasKey("Id");

                    b.ToTable("User", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartment", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<int>("LoginMethodType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("LoginType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer")
                        .HasComment("");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<bool>("RefreshTokenIsAvailable")
                        .HasColumnType("boolean")
                        .HasComment("");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken", t =>
                        {
                            t.HasComment("");
                        });
                });

            modelBuilder.Entity("Yuque.Core.Entities.Schedules.ScheduleTaskRecord", b =>
                {
                    b.HasOne("Yuque.Core.Entities.Schedules.ScheduleTask", "ScheduleTask")
                        .WithMany()
                        .HasForeignKey("ScheduleTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleTask");
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.HasOne("Yuque.Core.Entities.SystemManagement.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.MenuResource", b =>
                {
                    b.HasOne("Yuque.Core.Entities.SystemManagement.ApiResource", "ApiResource")
                        .WithMany()
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yuque.Core.Entities.SystemManagement.Menu", "Menu")
                        .WithMany("Resources")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiResource");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.Permission", b =>
                {
                    b.HasOne("Yuque.Core.Entities.SystemManagement.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yuque.Core.Entities.Users.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserDepartment", b =>
                {
                    b.HasOne("Yuque.Core.Entities.SystemManagement.Region", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yuque.Core.Entities.Users.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserRole", b =>
                {
                    b.HasOne("Yuque.Core.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yuque.Core.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.UserToken", b =>
                {
                    b.HasOne("Yuque.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuque.Core.Entities.SystemManagement.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Yuque.Core.Entities.Users.User", b =>
                {
                    b.Navigation("UserDepartments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
